development:
  adapter: postgresql
  encoding: unicode
  database: skyservice_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: skyservice_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: skyservice_prouction
  pool: 5
  username:
  password:
